[target.thumbv6m-none-eabi]
runner = "arm-none-eabi-gdb"
#rustflags = ["-C", "link-arg=-Tlink.x", "-C", "linker=arm-none-eabi-ld" ]
rustflags = ["-C", "link-arg=-Tlink.x"]

[build]
target = "thumbv6m-none-eabi"
