[package]
name = "interrupt"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.5.7"
cortex-m-rt = "0.6.3"
panic-halt = "0.2.0"
cortex-m-semihosting = "0.5.0"
#panic-semihosting = "0.6.0"
